version: '3.8'

services:
  waha:
    image: devlikeapro/waha
    container_name: waha-server
    ports:
      - "3000:3000"
    environment:
      - API_ENABLED=true
      - API_KEY=berhasil123
      - ENGINE=nowjs
      - SESSIONS=default
      - LOG_LEVEL=info
      - CORS_ENABLED=true
      - CORS_ORIGIN=*
      - WEBHOOK_URL=http://localhost:3001/webhook
      - WEBHOOK_EVENTS=message,ack
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - wa-bot-network

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: wa-bot
    ports:
      - "3001:3001"
    environment:
      - WAHA_API_URL=http://waha:3000
      - WAHA_API_KEY=berhasil123
      - WAHA_SESSION_NAME=default
      - GROQ_API_KEY=${GROQ_API_KEY}
      - BOT_COMMAND_KEY=!P
      - BOT_NAME=WA Bot
      - SIMULATION_MODE=false
      - PORT=3001
    depends_on:
      - waha
    restart: unless-stopped
    networks:
      - wa-bot-network

networks:
  wa-bot-network:
    driver: bridge

volumes:
  sessions:
  logs: